# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_card', models.CharField(blank=True, choices=[('BNI', 'BNI'), ('BCA', 'BCA'), ('MANDIRI', 'MANDIRI'), ('MEGA', 'MEGA'), ('NONE', 'NONE')], default='NONE', max_length=20)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('summary', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('picture_link', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=256)),
                ('category', models.CharField(blank=True, choices=[('FASHION', 'FASHION'), ('ELECTRONIC', 'ELECTRONIC'), ('FOOD_AND_BEVERAGE', 'Food and Beverage')], max_length=256)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('location', models.CharField(blank=True, choices=[('MALL_KELAPA_GADING', 'Mall Kelapa Gading'), ('GRAND_INDONESIA', 'Grand Indonesia'), ('PONDOK_INDAH_MALL_1', 'Pondok Indah Mall 1'), ('PONDOK_INDAH_MALL_2', 'Pondok Indah Mall 2'), ('PONDOK_INDAH_MALL_3', 'Pondok Indah Mall 3')], max_length=256)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('picture_link', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='retailer_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='luarbiasa.Retailer'),
        ),
    ]
